project_name: thesis

# Output file names
output_paper: output/thesis_paper.pdf

# Possible values: debug, info, warn, error, fatal, off
# The repo code only uses info and error levels so info is a good default
log_level: info

# Path to the log file - set to 'stdout' to log to console
log_file: stdout

# External data paths
sample_all_listed: data/external/sample_all_listed_firms.csv

# Result objects
results_r: output/results.rda

# Quarto documents
paper_r: paper/paper_r.qmd

